// <auto-generated />
#nullable enable
namespace ABACUS.CRM;

/// <summary>
/// Generated DTO proof from OpenAPI / Hub pipeline (Vague 6). Regenerate via scripts/generate-dtos.ps1.
/// </summary>
public sealed partial class SubjectGenerated
{
    public string? Id { get; set; }
    public string? Name { get; set; }
    public long? SubjectNumber { get; set; }
    public string? Email { get; set; }
}
