<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ABACUS.CORE\ABACUS.Core.csproj" />
    <ProjectReference Include="..\ABACUS.AccountsPayable\ABACUS.AccountsPayable.csproj" />
    <ProjectReference Include="..\ABACUS.AccountsReceivable\ABACUS.AccountsReceivable.csproj" />
    <ProjectReference Include="..\ABACUS.AssetsLedger\ABACUS.AssetsLedger.csproj" />
    <ProjectReference Include="..\ABACUS.CRM\ABACUS.CRM.csproj" />
    <ProjectReference Include="..\ABACUS.Finance\ABACUS.Finance.csproj" />
    <ProjectReference Include="..\ABACUS.General\ABACUS.General.csproj" />
    <ProjectReference Include="..\ABACUS.RealEstate\ABACUS.RealEstate.csproj" />
    <ProjectReference Include="..\ABACUS.Subscription\ABACUS.Subscription.csproj" />
    <ProjectReference Include="..\ABACUS.AbaReport\ABACUS.AbaReport.csproj" />
    <ProjectReference Include="..\ABACUS.WebShop\ABACUS.WebShop.csproj" />
    <ProjectReference Include="..\ABACUS.FieldInformation\ABACUS.FieldInformation.csproj" />
    <ProjectReference Include="..\ABACUS.DependencyInjection\ABACUS.DependencyInjection.csproj" />
    <ProjectReference Include="..\ABACUS.Testing\ABACUS.Testing.csproj" />
    <ProjectReference Include="..\ABACUS.HumanResources\ABACUS.HumanResources.csproj" />
    <ProjectReference Include="..\ABACUS.Salary\ABACUS.Salary.csproj" />
    <ProjectReference Include="..\ABACUS.ProjectManagement\ABACUS.ProjectManagement.csproj" />
    <ProjectReference Include="..\ABACUS.ProductionPlanning\ABACUS.ProductionPlanning.csproj" />
    <ProjectReference Include="..\ABACUS.DossierFileUpload\ABACUS.DossierFileUpload.csproj" />
    <ProjectReference Include="..\ABACUS.UserDependentAuth\ABACUS.UserDependentAuth.csproj" />
    <ProjectReference Include="..\ABACUS.Generators\ABACUS.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="ABACUS.Testing" />
  </ItemGroup>

</Project>
