using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ABACUS.Generators;

[Generator]
public sealed class AbacusFieldMappingGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "ABACUS.Core.AbacusFieldAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var types = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeMetadataName,
                static (node, _) => node is PropertyDeclarationSyntax,
                static (ctx, _) => ctx.TargetSymbol as IPropertySymbol)
            .Where(static p => p is not null)
            .Collect();

        context.RegisterSourceOutput(types, static (spc, properties) => Execute(spc, properties!));
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<IPropertySymbol?> properties)
    {
        var byType = properties
            .Where(p => p is not null)
            .GroupBy(p => p!.ContainingType, SymbolEqualityComparer.Default)
            .ToList();

        if (byType.Count == 0)
        {
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using ABACUS.Core;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace ABACUS.Core.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Source-generated helpers for [AbacusField] mappings.</summary>");
        sb.AppendLine("public static class AbacusFieldMappingGenerated");
        sb.AppendLine("{");

        foreach (var group in byType)
        {
            var type = group.Key!;
            var typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var entityName = type.Name;
            var safeName = Sanitize(type.Name);

            sb.AppendLine($"    /// <summary>Applies [AbacusField] mappings for {entityName}.</summary>");
            sb.AppendLine($"    public static AbacusFieldMappingBuilder Apply{safeName}(this AbacusFieldMappingBuilder builder)");
            sb.AppendLine("    {");
            sb.AppendLine("        ArgumentNullException.ThrowIfNull(builder);");
            sb.AppendLine($"        builder = builder.Entity(\"{Escape(entityName)}\");");

            foreach (var prop in group)
            {
                var attr = prop!.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == AttributeMetadataName);
                if (attr is null || attr.ConstructorArguments.Length == 0)
                {
                    continue;
                }

                var path = attr.ConstructorArguments[0].Value as string;
                if (string.IsNullOrWhiteSpace(path))
                {
                    continue;
                }

                sb.AppendLine(
                    $"        builder = builder.Field(\"{Escape(prop.Name)}\", \"{Escape(path!)}\");");
            }

            sb.AppendLine("        return builder;");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine($"    /// <summary>Registers field mapping for {entityName} from attributes.</summary>");
            sb.AppendLine(
                $"    public static IServiceCollection AddAbacusFieldMappingFromAttributes_{safeName}(this IServiceCollection services)");
            sb.AppendLine("    {");
            sb.AppendLine("        ArgumentNullException.ThrowIfNull(services);");
            sb.AppendLine($"        return services.AddAbacusFieldMapping(b => b.Apply{safeName}());");
            sb.AppendLine("    }");
            sb.AppendLine();
            _ = typeName; // keep for future typed overloads
        }

        sb.AppendLine("}");
        context.AddSource("AbacusFieldMappingGenerated.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string Sanitize(string name)
    {
        var chars = name.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray();
        return new string(chars);
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
