// <auto-generated />
#nullable enable
namespace ABACUS.Finance;

/// <summary>
/// Generated DTO proof from OpenAPI / Hub pipeline (Vague 6). Regenerate via scripts/generate-dtos.ps1.
/// </summary>
public sealed partial class AccountGenerated
{
    public string? Id { get; set; }
    public string? EnterpriseId { get; set; }
    public string? Name { get; set; }
    public string? AccountNumber { get; set; }
}
