# Generates minimal typed DTO records from curated OpenAPI YAML (proof entities).
# Usage: pwsh ./scripts/generate-dtos.ps1
# After a full Hub import via import-openapi.ps1, re-run this script.
# Future: generate from $metadata CSDL instead of OpenAPI schemas.

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot

function Write-GeneratedDto {
    param(
        [string]$ProjectDir,
        [string]$Namespace,
        [string]$TypeName,
        [string[]]$Properties
    )

    $dir = Join-Path (Join-Path $root $ProjectDir) "Models"
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
    $path = Join-Path $dir "$TypeName.g.cs"

    $props = ($Properties | ForEach-Object { "    public $_ { get; set; }" }) -join "`n"
    $content = @"
// <auto-generated />
#nullable enable
namespace $Namespace;

/// <summary>
/// Generated DTO proof from OpenAPI / Hub pipeline (Vague 6). Regenerate via scripts/generate-dtos.ps1.
/// </summary>
public sealed partial class $TypeName
{
$props
}
"@
    Set-Content -Path $path -Value $content -Encoding UTF8
    Write-Host "Wrote $path"
}

# Curated property sets (OpenAPI schemas are often open/additionalProperties).
Write-GeneratedDto "ABACUS.Finance" "ABACUS.Finance" "AccountGenerated" @(
    "string? Id",
    "string? EnterpriseId",
    "string? Name",
    "string? AccountNumber"
)
Write-GeneratedDto "ABACUS.AssetsLedger" "ABACUS.AssetsLedger" "AssetGenerated" @(
    "string? Id",
    "string? Name",
    "string? AssetNumber",
    "string? CategoryId"
)
Write-GeneratedDto "ABACUS.CRM" "ABACUS.CRM" "SubjectGenerated" @(
    "string? Id",
    "string? Name",
    "long? SubjectNumber",
    "string? Email"
)

Write-Host ""
Write-Host "Done. Hub `$metadata auto-generation is documented in ABACUS.CORE/README.md (out of auto scope)."
