openapi: 3.0.0
info:
  title: General
  version: 1.0.0
  description: Abacus General entity API (partial OpenAPI used for NSwag generation).
servers:
  - url: http://localhost
paths:
  /BeneficiaryAccounts:
    get:
      summary: List beneficiary accounts
      operationId: get_BeneficiaryAccounts
      tags:
        - AnlageInfos
      parameters:
        - $ref: '#/components/parameters/ODataFilter'
        - $ref: '#/components/parameters/ODataSelect'
        - $ref: '#/components/parameters/ODataTop'
        - $ref: '#/components/parameters/ODataOrderBy'
        - $ref: '#/components/parameters/ODataExpand'
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ODataCollection'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /Countries:
    get:
      summary: List countries
      operationId: get_Countries
      tags:
        - AnlageInfos
      parameters:
        - $ref: '#/components/parameters/ODataFilter'
        - $ref: '#/components/parameters/ODataSelect'
        - $ref: '#/components/parameters/ODataTop'
        - $ref: '#/components/parameters/ODataOrderBy'
        - $ref: '#/components/parameters/ODataExpand'
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ODataCollection'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /Currencies:
    get:
      summary: List currencies
      operationId: get_Currencies
      tags:
        - AnlageInfos
      parameters:
        - $ref: '#/components/parameters/ODataFilter'
        - $ref: '#/components/parameters/ODataSelect'
        - $ref: '#/components/parameters/ODataTop'
        - $ref: '#/components/parameters/ODataOrderBy'
        - $ref: '#/components/parameters/ODataExpand'
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ODataCollection'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /Divisions:
    get:
      summary: List divisions
      operationId: get_Divisions
      tags:
        - AnlageInfos
      parameters:
        - $ref: '#/components/parameters/ODataFilter'
        - $ref: '#/components/parameters/ODataSelect'
        - $ref: '#/components/parameters/ODataTop'
        - $ref: '#/components/parameters/ODataOrderBy'
        - $ref: '#/components/parameters/ODataExpand'
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ODataCollection'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /Enterprises:
    get:
      summary: List enterprises
      operationId: get_Enterprises
      tags:
        - AnlageInfos
      parameters:
        - $ref: '#/components/parameters/ODataFilter'
        - $ref: '#/components/parameters/ODataSelect'
        - $ref: '#/components/parameters/ODataTop'
        - $ref: '#/components/parameters/ODataOrderBy'
        - $ref: '#/components/parameters/ODataExpand'
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ODataCollection'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /ExchangeRates:
    get:
      summary: List exchange rates
      operationId: get_ExchangeRates
      tags:
        - AnlageInfos
      parameters:
        - $ref: '#/components/parameters/ODataFilter'
        - $ref: '#/components/parameters/ODataSelect'
        - $ref: '#/components/parameters/ODataTop'
        - $ref: '#/components/parameters/ODataOrderBy'
        - $ref: '#/components/parameters/ODataExpand'
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ODataCollection'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /FinancialInstitutes:
    get:
      summary: List financial institutes
      operationId: get_FinancialInstitutes
      tags:
        - AnlageInfos
      parameters:
        - $ref: '#/components/parameters/ODataFilter'
        - $ref: '#/components/parameters/ODataSelect'
        - $ref: '#/components/parameters/ODataTop'
        - $ref: '#/components/parameters/ODataOrderBy'
        - $ref: '#/components/parameters/ODataExpand'
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ODataCollection'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /StorageFolders:
    get:
      summary: List storage folders
      operationId: get_StorageFolders
      tags:
        - AnlageInfos
      parameters:
        - $ref: '#/components/parameters/ODataFilter'
        - $ref: '#/components/parameters/ODataSelect'
        - $ref: '#/components/parameters/ODataTop'
        - $ref: '#/components/parameters/ODataOrderBy'
        - $ref: '#/components/parameters/ODataExpand'
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ODataCollection'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /Storages:
    get:
      summary: List storages
      operationId: get_Storages
      tags:
        - AnlageInfos
      parameters:
        - $ref: '#/components/parameters/ODataFilter'
        - $ref: '#/components/parameters/ODataSelect'
        - $ref: '#/components/parameters/ODataTop'
        - $ref: '#/components/parameters/ODataOrderBy'
        - $ref: '#/components/parameters/ODataExpand'
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ODataCollection'
        '400':
          description: Bad Request
        '500':
          description: Server Error
  /$batch:
    post:
      summary: OData batch
      operationId: post_batch
      tags:
        - Batch
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: Successful
        '400':
          description: Bad Request
        '500':
          description: Server Error
components:
  parameters:
    ODataFilter:
      name: $filter
      in: query
      required: false
      schema:
        type: string
    ODataSelect:
      name: $select
      in: query
      required: false
      schema:
        type: string
    ODataTop:
      name: $top
      in: query
      required: false
      schema:
        type: integer
        maximum: 100
    ODataOrderBy:
      name: $orderby
      in: query
      required: false
      schema:
        type: string
    ODataExpand:
      name: $expand
      in: query
      required: false
      schema:
        type: string
  schemas:
    ODataCollection:
      type: object
      properties:
        value:
          type: array
          items:
            type: object
            additionalProperties: true
        '@odata.nextLink':
          type: string
          nullable: true
