// <auto-generated />
#nullable enable
namespace ABACUS.AssetsLedger;

/// <summary>
/// Generated DTO proof from OpenAPI / Hub pipeline (Vague 6). Regenerate via scripts/generate-dtos.ps1.
/// </summary>
public sealed partial class AssetGenerated
{
    public string? Id { get; set; }
    public string? Name { get; set; }
    public string? AssetNumber { get; set; }
    public string? CategoryId { get; set; }
}
